// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package language

import "golang.org/x/text/language/internal"

// CLDRVersion is the CLDR version from which the tables in this package are derived.
const CLDRVersion = "32"

const (
	_af  = 22
	_am  = 39
	_ar  = 58
	_az  = 88
	_bg  = 126
	_bn  = 165
	_ca  = 215
	_cs  = 250
	_da  = 257
	_de  = 269
	_el  = 310
	_en  = 313
	_es  = 318
	_et  = 320
	_fa  = 328
	_fi  = 337
	_fil = 339
	_fr  = 350
	_gu  = 420
	_he  = 444
	_hi  = 446
	_hr  = 465
	_hu  = 469
	_hy  = 471
	_id  = 481
	_is  = 504
	_it  = 505
	_ja  = 512
	_ka  = 528
	_kk  = 578
	_km  = 586
	_kn  = 593
	_ko  = 596
	_ky  = 650
	_lo  = 696
	_lt  = 704
	_lv  = 711
	_mk  = 767
	_ml  = 772
	_mn  = 779
	_mo  = 784
	_mr  = 795
	_ms  = 799
	_mul = 806
	_my  = 817
	_nb  = 839
	_ne  = 849
	_nl  = 871
	_no  = 879
	_pa  = 925
	_pl  = 947
	_pt  = 960
	_ro  = 988
	_ru  = 994
	_sh  = 1031
	_si  = 1036
	_sk  = 1042
	_sl  = 1046
	_sq  = 1073
	_sr  = 1074
	_sv  = 1092
	_sw  = 1093
	_ta  = 1104
	_te  = 1121
	_th  = 1131
	_tl  = 1146
	_tn  = 1152
	_tr  = 1162
	_uk  = 1198
	_ur  = 1204
	_uz  = 1212
	_vi  = 1219
	_zh  = 1321
	_zu  = 1327
	_jbo = 515
	_ami = 1650
	_bnn = 2357
	_hak = 438
	_tlh = 14467
	_lb  = 661
	_nv  = 899
	_pwn = 12055
	_tao = 14188
	_tay = 14198
	_tsu = 14662
	_nn  = 874
	_sfb = 13629
	_vgt = 15701
	_sgg = 13660
	_cmn = 3007
	_nan = 835
	_hsn = 467
)
const (
	_001 = 1
	_419 = 31
	_BR  = 65
	_CA  = 73
	_ES  = 110
	_GB  = 123
	_MD  = 188
	_PT  = 238
	_UK  = 306
	_US  = 309
	_ZZ  = 357
	_XA  = 323
	_XC  = 325
	_XK  = 333
)
const (
	_Latn = 87
	_Hani = 54
	_Hans = 56
	_Hant = 57
	_Qaaa = 139
	_Qaai = 147
	_Qabx = 188
	_Zinh = 236
	_Zyyy = 241
	_Zzzz = 242
)

// NumCompactTags is the number of common tags. The maximum tag is
// NumCompactTags-1.
const NumCompactTags = 775
const (
	xund          compactID = 0
	xaf           compactID = 1
	xafNA         compactID = 2
	xafZA         compactID = 3
	xagq          compactID = 4
	xagqCM        compactID = 5
	xak           compactID = 6
	xakGH         compactID = 7
	xam           compactID = 8
	xamET         compactID = 9
	xar           compactID = 10
	xar001        compactID = 11
	xarAE         compactID = 12
	xarBH         compactID = 13
	xarDJ         compactID = 14
	xarDZ         compactID = 15
	xarEG         compactID = 16
	xarEH         compactID = 17
	xarER         compactID = 18
	xarIL         compactID = 19
	xarIQ         compactID = 20
	xarJO         compactID = 21
	xarKM         compactID = 22
	xarKW         compactID = 23
	xarLB         compactID = 24
	xarLY         compactID = 25
	xarMA         compactID = 26
	xarMR         compactID = 27
	xarOM         compactID = 28
	xarPS         compactID = 29
	xarQA         compactID = 30
	xarSA         compactID = 31
	xarSD         compactID = 32
	xarSO         compactID = 33
	xarSS         compactID = 34
	xarSY         compactID = 35
	xarTD         compactID = 36
	xarTN         compactID = 37
	xarYE         compactID = 38
	xars          compactID = 39
	xas           compactID = 40
	xasIN         compactID = 41
	xasa          compactID = 42
	xasaTZ        compactID = 43
	xast          compactID = 44
	xastES        compactID = 45
	xaz           compactID = 46
	xazCyrl       compactID = 47
	xazCyrlAZ     compactID = 48
	xazLatn       compactID = 49
	xazLatnAZ     compactID = 50
	xbas          compactID = 51
	xbasCM        compactID = 52
	xbe           compactID = 53
	xbeBY         compactID = 54
	xbem          compactID = 55
	xbemZM        compactID = 56
	xbez          compactID = 57
	xbezTZ        compactID = 58
	xbg           compactID = 59
	xbgBG         compactID = 60
	xbh           compactID = 61
	xbm           compactID = 62
	xbmML         compactID = 63
	xbn           compactID = 64
	xbnBD         compactID = 65
	xbnIN         compactID = 66
	xbo           compactID = 67
	xboCN         compactID = 68
	xboIN         compactID = 69
	xbr           compactID = 70
	xbrFR         compactID = 71
	xbrx          compactID = 72
	xbrxIN        compactID = 73
	xbs           compactID = 74
	xbsCyrl       compactID = 75
	xbsCyrlBA     compactID = 76
	xbsLatn       compactID = 77
	xbsLatnBA     compactID = 78
	xca           compactID = 79
	xcaAD         compactID = 80
	xcaES         compactID = 81
	xcaFR         compactID = 82
	xcaIT         compactID = 83
	xccp          compactID = 84
	xccpBD        compactID = 85
	xccpIN        compactID = 86
	xce           compactID = 87
	xceRU         compactID = 88
	xcgg          compactID = 89
	xcggUG        compactID = 90
	xchr          compactID = 91
	xchrUS        compactID = 92
	xckb          compactID = 93
	xckbIQ        compactID = 94
	xckbIR        compactID = 95
	xcs           compactID = 96
	xcsCZ         compactID = 97
	xcu           compactID = 98
	xcuRU         compactID = 99
	xcy           compactID = 100
	xcyGB         compactID = 101
	xda           compactID = 102
	xdaDK         compactID = 103
	xdaGL         compactID = 104
	xdav          compactID = 105
	xdavKE        compactID = 106
	xde           compactID = 107
	xdeAT         compactID = 108
	xdeBE         compactID = 109
	xdeCH         compactID = 110
	xdeDE         compactID = 111
	xdeIT         compactID = 112
	xdeLI         compactID = 113
	xdeLU         compactID = 114
	xdje          compactID = 115
	xdjeNE        compactID = 116
	xdsb          compactID = 117
	xdsbDE        compactID = 118
	xdua          compactID = 119
	xduaCM        compactID = 120
	xdv           compactID = 121
	xdyo          compactID = 122
	xdyoSN        compactID = 123
	xdz           compactID = 124
	xdzBT         compactID = 125
	xebu          compactID = 126
	xebuKE        compactID = 127
	xee           compactID = 128
	xeeGH         compactID = 129
	xeeTG         compactID = 130
	xel           compactID = 131
	xelCY         compactID = 132
	xelGR         compactID = 133
	xen           compactID = 134
	xen001        compactID = 135
	xen150        compactID = 136
	xenAG         compactID = 137
	xenAI         compactID = 138
	xenAS         compactID = 139
	xenAT         compactID = 140
	xenAU         compactID = 141
	xenBB         compactID = 142
	xenBE         compactID = 143
	xenBI         compactID = 144
	xenBM         compactID = 145
	xenBS         compactID = 146
	xenBW         compactID = 147
	xenBZ         compactID = 148
	xenCA         compactID = 149
	xenCC         compactID = 150
	xenCH         compactID = 151
	xenCK         compactID = 152
	xenCM         compactID = 153
	xenCX         compactID = 154
	xenCY         compactID = 155
	xenDE         compactID = 156
	xenDG         compactID = 157
	xenDK         compactID = 158
	xenDM         compactID = 159
	xenER         compactID = 160
	xenFI         compactID = 161
	xenFJ         compactID = 162
	xenFK         compactID = 163
	xenFM         compactID = 164
	xenGB         compactID = 165
	xenGD         compactID = 166
	xenGG         compactID = 167
	xenGH         compactID = 168
	xenGI         compactID = 169
	xenGM         compactID = 170
	xenGU         compactID = 171
	xenGY         compactID = 172
	xenHK         compactID = 173
	xenIE         compactID = 174
	xenIL         compactID = 175
	xenIM         compactID = 176
	xenIN         compactID = 177
	xenIO         compactID = 178
	xenJE         compactID = 179
	xenJM         compactID = 180
	xenKE         compactID = 181
	xenKI         compactID = 182
	xenKN         compactID = 183
	xenKY         compactID = 184
	xenLC         compactID = 185
	xenLR         compactID = 186
	xenLS         compactID = 187
	xenMG         compactID = 188
	xenMH         compactID = 189
	xenMO         compactID = 190
	xenMP         compactID = 191
	xenMS         compactID = 192
	xenMT         compactID = 193
	xenMU         compactID = 194
	xenMW         compactID = 195
	xenMY         compactID = 196
	xenNA         compactID = 197
	xenNF         compactID = 198
	xenNG         compactID = 199
	xenNL         compactID = 200
	xenNR         compactID = 201
	xenNU         compactID = 202
	xenNZ         compactID = 203
	xenPG         compactID = 204
	xenPH         compactID = 205
	xenPK         compactID = 206
	xenPN         compactID = 207
	xenPR         compactID = 208
	xenPW         compactID = 209
	xenRW         compactID = 210
	xenSB         compactID = 211
	xenSC         compactID = 212
	xenSD         compactID = 213
	xenSE         compactID = 214
	xenSG         compactID = 215
	xenSH         compactID = 216
	xenSI         compactID = 217
	xenSL         compactID = 218
	xenSS         compactID = 219
	xenSX         compactID = 220
	xenSZ         compactID = 221
	xenTC         compactID = 222
	xenTK         compactID = 223
	xenTO         compactID = 224
	xenTT         compactID = 225
	xenTV         compactID = 226
	xenTZ         compactID = 227
	xenUG         compactID = 228
	xenUM         compactID = 229
	xenUS         compactID = 230
	xenVC         compactID = 231
	xenVG         compactID = 232
	xenVI         compactID = 233
	xenVU         compactID = 234
	xenWS         compactID = 235
	xenZA         compactID = 236
	xenZM         compactID = 237
	xenZW         compactID = 238
	xeo           compactID = 239
	xeo001        compactID = 240
	xes           compactID = 241
	xes419        compactID = 242
	xesAR         compactID = 243
	xesBO         compactID = 244
	xesBR         compactID = 245
	xesBZ         compactID = 246
	xesCL         compactID = 247
	xesCO         compactID = 248
	xesCR         compactID = 249
	xesCU         compactID = 250
	xesDO         compactID = 251
	xesEA         compactID = 252
	xesEC         compactID = 253
	xesES         compactID = 254
	xesGQ         compactID = 255
	xesGT         compactID = 256
	xesHN         compactID = 257
	xesIC         compactID = 258
	xesMX         compactID = 259
	xesNI         compactID = 260
	xesPA         compactID = 261
	xesPE         compactID = 262
	xesPH         compactID = 263
	xesPR         compactID = 264
	xesPY         compactID = 265
	xesSV         compactID = 266
	xesUS         compactID = 267
	xesUY         compactID = 268
	xesVE         compactID = 269
	xet           compactID = 270
	xetEE         compactID = 271
	xeu           compactID = 272
	xeuES         compactID = 273
	xewo          compactID = 274
	xewoCM        compactID = 275
	xfa           compactID = 276
	xfaAF         compactID = 277
	xfaIR         compactID = 278
	xff           compactID = 279
	xffCM         compactID = 280
	xffGN         compactID = 281
	xffMR         compactID = 282
	xffSN         compactID = 283
	xfi           compactID = 284
	xfiFI         compactID = 285
	xfil          compactID = 286
	xfilPH        compactID = 287
	xfo           compactID = 288
	xfoDK         compactID = 289
	xfoFO         compactID = 290
	xfr           compactID = 291
	xfrBE         compactID = 292
	xfrBF         compactID = 293
	xfrBI         compactID = 294
	xfrBJ         compactID = 295
	xfrBL         compactID = 296
	xfrCA         compactID = 297
	xfrCD         compactID = 298
	xfrCF         compactID = 299
	xfrCG         compactID = 300
	xfrCH         compactID = 301
	xfrCI         compactID = 302
	xfrCM         compactID = 303
	xfrDJ         compactID = 304
	xfrDZ         compactID = 305
	xfrFR         compactID = 306
	xfrGA         compactID = 307
	xfrGF         compactID = 308
	xfrGN         compactID = 309
	xfrGP         compactID = 310
	xfrGQ         compactID = 311
	xfrHT         compactID = 312
	xfrKM         compactID = 313
	xfrLU         compactID = 314
	xfrMA         compactID = 315
	xfrMC         compactID = 316
	xfrMF         compactID = 317
	xfrMG         compactID = 318
	xfrML         compactID = 319
	xfrMQ         compactID = 320
	xfrMR         compactID = 321
	xfrMU         compactID = 322
	xfrNC         compactID = 323
	xfrNE         compactID = 324
	xfrPF         compactID = 325
	xfrPM         compactID = 326
	xfrRE         compactID = 327
	xfrRW         compactID = 328
	xfrSC         compactID = 329
	xfrSN         compactID = 330
	xfrSY         compactID = 331
	xfrTD         compactID = 332
	xfrTG         compactID = 333
	xfrTN         compactID = 334
	xfrVU         compactID = 335
	xfrWF         compactID = 336
	xfrYT         compactID = 337
	xfur          compactID = 338
	xfurIT        compactID = 339
	xfy           compactID = 340
	xfyNL         compactID = 341
	xga           compactID = 342
	xgaIE         compactID = 343
	xgd           compactID = 344
	xgdGB         compactID = 345
	xgl           compactID = 346
	xglES         compactID = 347
	xgsw          compactID = 348
	xgswCH        compactID = 349
	xgswFR        compactID = 350
	xgswLI        compactID = 351
	xgu           compactID = 352
	xguIN         compactID = 353
	xguw          compactID = 354
	xguz          compactID = 355
	xguzKE        compactID = 356
	xgv           compactID = 357
	xgvIM         compactID = 358
	xha           compactID = 359
	xhaGH         compactID = 360
	xhaNE         compactID = 361
	xhaNG         compactID = 362
	xhaw          compactID = 363
	xhawUS        compactID = 364
	xhe           compactID = 365
	xheIL         compactID = 366
	xhi           compactID = 367
	xhiIN         compactID = 368
	xhr           compactID = 369
	xhrBA         compactID = 370
	xhrHR         compactID = 371
	xhsb          compactID = 372
	xhsbDE        compactID = 373
	xhu           compactID = 374
	xhuHU         compactID = 375
	xhy           compactID = 376
	xhyAM         compactID = 377
	xid           compactID = 378
	xidID         compactID = 379
	xig           compactID = 380
	xigNG         compactID = 381
	xii           compactID = 382
	xiiCN         compactID = 383
	xin           compactID = 384
	xio           compactID = 385
	xis           compactID = 386
	xisIS         compactID = 387
	xit           compactID = 388
	xitCH         compactID = 389
	xitIT         compactID = 390
	xitSM         compactID = 391
	xitVA         compactID = 392
	xiu           compactID = 393
	xiw           compactID = 394
	xja           compactID = 395
	xjaJP         compactID = 396
	xjbo          compactID = 397
	xjgo          compactID = 398
	xjgoCM        compactID = 399
	xji           compactID = 400
	xjmc          compactID = 401
	xjmcTZ        compactID = 402
	xjv           compactID = 403
	xjw           compactID = 404
	xka           compactID = 405
	xkaGE         compactID = 406
	xkab          compactID = 407
	xkabDZ        compactID = 408
	xkaj          compactID = 409
	xkam          compactID = 410
	xkamKE        compactID = 411
	xkcg          compactID = 412
	xkde          compactID = 413
	xkdeTZ        compactID = 414
	xkea          compactID = 415
	xkeaCV        compactID = 416
	xkhq          compactID = 417
	xkhqML        compactID = 418
	xki           compactID = 419
	xkiKE         compactID = 420
	xkk           compactID = 421
	xkkKZ         compactID = 422
	xkkj          compactID = 423
	xkkjCM        compactID = 424
	xkl           compactID = 425
	xklGL         compactID = 426
	xkln          compactID = 427
	xklnKE        compactID = 428
	xkm           compactID = 429
	xkmKH         compactID = 430
	xkn           compactID = 431
	xknIN         compactID = 432
	xko           compactID = 433
	xkoKP         compactID = 434
	xkoKR         compactID = 435
	xkok          compactID = 436
	xkokIN        compactID = 437
	xks           compactID = 438
	xksIN         compactID = 439
	xksb          compactID = 440
	xksbTZ        compactID = 441
	xksf          compactID = 442
	xksfCM        compactID = 443
	xksh          compactID = 444
	xkshDE        compactID = 445
	xku           compactID = 446
	xkw           compactID = 447
	xkwGB         compactID = 448
	xky           compactID = 449
	xkyKG         compactID = 450
	xlag          compactID = 451
	xlagTZ        compactID = 452
	xlb           compactID = 453
	xlbLU         compactID = 454
	xlg           compactID = 455
	xlgUG         compactID = 456
	xlkt          compactID = 457
	xlktUS        compactID = 458
	xln           compactID = 459
	xlnAO         compactID = 460
	xlnCD         compactID = 461
	xlnCF         compactID = 462
	xlnCG         compactID = 463
	xlo           compactID = 464
	xloLA         compactID = 465
	xlrc          compactID = 466
	xlrcIQ        compactID = 467
	xlrcIR        compactID = 468
	xlt           compactID = 469
	xltLT         compactID = 470
	xlu           compactID = 471
	xluCD         compactID = 472
	xluo          compactID = 473
	xluoKE        compactID = 474
	xluy          compactID = 475
	xluyKE        compactID = 476
	xlv           compactID = 477
	xlvLV         compactID = 478
	xmas          compactID = 479
	xmasKE        compactID = 480
	xmasTZ        compactID = 481
	xmer          compactID = 482
	xmerKE        compactID = 483
	xmfe          compactID = 484
	xmfeMU        compactID = 485
	xmg           compactID = 486
	xmgMG         compactID = 487
	xmgh          compactID = 488
	xmghMZ        compactID = 489
	xmgo          compactID = 490
	xmgoCM        compactID = 491
	xmk           compactID = 492
	xmkMK         compactID = 493
	xml           compactID = 494
	xmlIN         compactID = 495
	xmn           compactID = 496
	xmnMN         compactID = 497
	xmo           compactID = 498
	xmr           compactID = 499
	xmrIN         compactID = 500
	xms           compactID = 501
	xmsBN         compactID = 502
	xmsMY         compactID = 503
	xmsSG         compactID = 504
	xmt           compactID = 505
	xmtMT         compactID = 506
	xmua          compactID = 507
	xmuaCM        compactID = 508
	xmy           compactID = 509
	xmyMM         compactID = 510
	xmzn          compactID = 511
	xmznIR        compactID = 512
	xnah          compactID = 513
	xnaq          compactID = 514
	xnaqNA        compactID = 515
	xnb           compactID = 516
	xnbNO         compactID = 517
	xnbSJ         compactID = 518
	xnd           compactID = 519
	xndZW         compactID = 520
	xnds          compactID = 521
	xndsDE        compactID = 522
	xndsNL        compactID = 523
	xne           compactID = 524
	xneIN         compactID = 525
	xneNP         compactID = 526
	xnl           compactID = 527
	xnlAW         compactID = 528
	xnlBE         compactID = 529
	xnlBQ         compactID = 530
	xnlCW         compactID = 531
	xnlNL         compactID = 532
	xnlSR         compactID = 533
	xnlSX         compactID = 534
	xnmg          compactID = 535
	xnmgCM        compactID = 536
	xnn           compactID = 537
	xnnNO         compactID = 538
	xnnh          compactID = 539
	xnnhCM        compactID = 540
	xno           compactID = 541
	xnqo          compactID = 542
	xnr           compactID = 543
	xnso          compactID = 544
	xnus          compactID = 545
	xnusSS        compactID = 546
	xny           compactID = 547
	xnyn          compactID = 548
	xnynUG        compactID = 549
	xom           compactID = 550
	xomET         compactID = 551
	xomKE         compactID = 552
	xor           compactID = 553
	xorIN         compactID = 554
	xos           compactID = 555
	xosGE         compactID = 556
	xosRU         compactID = 557
	xpa           compactID = 558
	xpaArab       compactID = 559
	xpaArabPK     compactID = 560
	xpaGuru       compactID = 561
	xpaGuruIN     compactID = 562
	xpap          compactID = 563
	xpl           compactID = 564
	xplPL         compactID = 565
	xprg          compactID = 566
	xprg001       compactID = 567
	xps           compactID = 568
	xpsAF         compactID = 569
	xpt           compactID = 570
	xptAO         compactID = 571
	xptBR         compactID = 572
	xptCH         compactID = 573
	xptCV         compactID = 574
	xptGQ         compactID = 575
	xptGW         compactID = 576
	xptLU         compactID = 577
	xptMO         compactID = 578
	xptMZ         compactID = 579
	xptPT         compactID = 580
	xptST         compactID = 581
	xptTL         compactID = 582
	xqu           compactID = 583
	xquBO         compactID = 584
	xquEC         compactID = 585
	xquPE         compactID = 586
	xrm           compactID = 587
	xrmCH         compactID = 588
	xrn           compactID = 589
	xrnBI         compactID = 590
	xro           compactID = 591
	xroMD         compactID = 592
	xroRO         compactID = 593
	xrof          compactID = 594
	xrofTZ        compactID = 595
	xru           compactID = 596
	xruBY         compactID = 597
	xruKG         compactID = 598
	xruKZ         compactID = 599
	xruMD         compactID = 600
	xruRU         compactID = 601
	xruUA         compactID = 602
	xrw           compactID = 603
	xrwRW         compactID = 604
	xrwk          compactID = 605
	xrwkTZ        compactID = 606
	xsah          compactID = 607
	xsahRU        compactID = 608
	xsaq          compactID = 609
	xsaqKE        compactID = 610
	xsbp          compactID = 611
	xsbpTZ        compactID = 612
	xsd           compactID = 613
	xsdPK         compactID = 614
	xsdh          compactID = 615
	xse           compactID = 616
	xseFI         compactID = 617
	xseNO         compactID = 618
	xseSE         compactID = 619
	xseh          compactID = 620
	xsehMZ        compactID = 621
	xses          compactID = 622
	xsesML        compactID = 623
	xsg           compactID = 624
	xsgCF         compactID = 625
	xsh           compactID = 626
	xshi          compactID = 627
	xshiLatn      compactID = 628
	xshiLatnMA    compactID = 629
	xshiTfng      compactID = 630
	xshiTfngMA    compactID = 631
	xsi           compactID = 632
	xsiLK         compactID = 633
	xsk           compactID = 634
	xskSK         compactID = 635
	xsl           compactID = 636
	xslSI         compactID = 637
	xsma          compactID = 638
	xsmi          compactID = 639
	xsmj          compactID = 640
	xsmn          compactID = 641
	xsmnFI        compactID = 642
	xsms          compactID = 643
	xsn           compactID = 644
	xsnZW         compactID = 645
	xso           compactID = 646
	xsoDJ         compactID = 647
	xsoET         compactID = 648
	xsoKE         compactID = 649
	xsoSO         compactID = 650
	xsq           compactID = 651
	xsqAL         compactID = 652
	xsqMK         compactID = 653
	xsqXK         compactID = 654
	xsr           compactID = 655
	xsrCyrl       compactID = 656
	xsrCyrlBA     compactID = 657
	xsrCyrlME     compactID = 658
	xsrCyrlRS     compactID = 659
	xsrCyrlXK     compactID = 660
	xsrLatn       compactID = 661
	xsrLatnBA     compactID = 662
	xsrLatnME     compactID = 663
	xsrLatnRS     compactID = 664
	xsrLatnXK     compactID = 665
	xss           compactID = 666
	xssy          compactID = 667
	xst           compactID = 668
	xsv           compactID = 669
	xsvAX         compactID = 670
	xsvFI         compactID = 671
	xsvSE         compactID = 672
	xsw           compactID = 673
	xswCD         compactID = 674
	xswKE         compactID = 675
	xswTZ         compactID = 676
	xswUG         compactID = 677
	xsyr          compactID = 678
	xta           compactID = 679
	xtaIN         compactID = 680
	xtaLK         compactID = 681
	xtaMY         compactID = 682
	xtaSG         compactID = 683
	xte           compactID = 684
	xteIN         compactID = 685
	xteo          compactID = 686
	xteoKE        compactID = 687
	xteoUG        compactID = 688
	xtg           compactID = 689
	xtgTJ         compactID = 690
	xth           compactID = 691
	xthTH         compactID = 692
	xti           compactID = 693
	xtiER         compactID = 694
	xtiET         compactID = 695
	xtig          compactID = 696
	xtk           compactID = 697
	xtkTM         compactID = 698
	xtl           compactID = 699
	xtn           compactID = 700
	xto           compactID = 701
	xtoTO         compactID = 702
	xtr           compactID = 703
	xtrCY         compactID = 704
	xtrTR         compactID = 705
	xts           compactID = 706
	xtt           compactID = 707
	xttRU         compactID = 708
	xtwq          compactID = 709
	xtwqNE        compactID = 710
	xtzm          compactID = 711
	xtzmMA        compactID = 712
	xug           compactID = 713
	xugCN         compactID = 714
	xuk           compactID = 715
	xukUA         compactID = 716
	xur           compactID = 717
	xurIN         compactID = 718
	xurPK         compactID = 719
	xuz           compactID = 720
	xuzArab       compactID = 721
	xuzArabAF     compactID = 722
	xuzCyrl       compactID = 723
	xuzCyrlUZ     compactID = 724
	xuzLatn       compactID = 725
	xuzLatnUZ     compactID = 726
	xvai          compactID = 727
	xvaiLatn      compactID = 728
	xvaiLatnLR    compactID = 729
	xvaiVaii      compactID = 730
	xvaiVaiiLR    compactID = 731
	xve           compactID = 732
	xvi           compactID = 733
	xviVN         compactID = 734
	xvo           compactID = 735
	xvo001        compactID = 736
	xvun          compactID = 737
	xvunTZ        compactID = 738
	xwa           compactID = 739
	xwae          compactID = 740
	xwaeCH        compactID = 741
	xwo           compactID = 742
	xwoSN         compactID = 743
	xxh           compactID = 744
	xxog          compactID = 745
	xxogUG        compactID = 746
	xyav          compactID = 747
	xyavCM        compactID = 748
	xyi           compactID = 749
	xyi001        compactID = 750
	xyo           compactID = 751
	xyoBJ         compactID = 752
	xyoNG         compactID = 753
	xyue          compactID = 754
	xyueHans      compactID = 755
	xyueHansCN    compactID = 756
	xyueHant      compactID = 757
	xyueHantHK    compactID = 758
	xzgh          compactID = 759
	xzghMA        compactID = 760
	xzh           compactID = 761
	xzhHans       compactID = 762
	xzhHansCN     compactID = 763
	xzhHansHK     compactID = 764
	xzhHansMO     compactID = 765
	xzhHansSG     compactID = 766
	xzhHant       compactID = 767
	xzhHantHK     compactID = 768
	xzhHantMO     compactID = 769
	xzhHantTW     compactID = 770
	xzu           compactID = 771
	xzuZA         compactID = 772
	xcaESvalencia compactID = 773
	xenUSuvaposix compactID = 774
)

var coreTags = []language.CompactCoreInfo{ // 773 elements
	// Entry 0 - 1F
	0x00000000, 0x01600000, 0x016000d2, 0x01600161,
	0x01c00000, 0x01c00052, 0x02100000, 0x02100080,
	0x02700000, 0x0270006f, 0x03a00000, 0x03a00001,
	0x03a00023, 0x03a00039, 0x03a00062, 0x03a00067,
	0x03a0006b, 0x03a0006c, 0x03a0006d, 0x03a00097,
	0x03a0009b, 0x03a000a1, 0x03a000a8, 0x03a000ac,
	0x03a000b0, 0x03a000b9, 0x03a000ba, 0x03a000c9,
	0x03a000e1, 0x03a000ed, 0x03a000f3, 0x03a00108,
	// Entry 20 - 3F
	0x03a0010b, 0x03a00115, 0x03a00117, 0x03a0011c,
	0x03a00120, 0x03a00128, 0x03a0015e, 0x04000000,
	0x04300000, 0x04300099, 0x04400000, 0x0440012f,
	0x04800000, 0x0480006e, 0x05800000, 0x0581f000,
	0x0581f032, 0x05857000, 0x05857032, 0x05e00000,
	0x05e00052, 0x07100000, 0x07100047, 0x07500000,
	0x07500162, 0x07900000, 0x0790012f, 0x07e00000,
	0x07e00038, 0x08200000, 0x0a000000, 0x0a0000c3,
	// Entry 40 - 5F
	0x0a500000, 0x0a500035, 0x0a500099, 0x0a900000,
	0x0a900053, 0x0a900099, 0x0b200000, 0x0b200078,
	0x0b500000, 0x0b500099, 0x0b700000, 0x0b71f000,
	0x0b71f033, 0x0b757000, 0x0b757033, 0x0d700000,
	0x0d700022, 0x0d70006e, 0x0d700078, 0x0d70009e,
	0x0db00000, 0x0db00035, 0x0db00099, 0x0dc00000,
	0x0dc00106, 0x0df00000, 0x0df00131, 0x0e500000,
	0x0e500135, 0x0e900000, 0x0e90009b, 0x0e90009c,
	// Entry 60 - 7F
	0x0fa00000, 0x0fa0005e, 0x0fe00000, 0x0fe00106,
	0x10000000, 0x1000007b, 0x10100000, 0x10100063,
	0x10100082, 0x10800000, 0x108000a4, 0x10d00000,
	0x10d0002e, 0x10d00036, 0x10d0004e, 0x10d00060,
	0x10d0009e, 0x10d000b2, 0x10d000b7, 0x11700000,
	0x117000d4, 0x11f00000, 0x11f00060, 0x12400000,
	0x12400052, 0x12800000, 0x12b00000, 0x12b00114,
	0x12d00000, 0x12d00043, 0x12f00000, 0x12f000a4,
	// Entry 80 - 9F
	0x13000000, 0x13000080, 0x13000122, 0x13600000,
	0x1360005d, 0x13600087, 0x13900000, 0x13900001,
	0x1390001a, 0x13900025, 0x13900026, 0x1390002d,
	0x1390002e, 0x1390002f, 0x13900034, 0x13900036,
	0x1390003a, 0x1390003d, 0x13900042, 0x13900046,
	0x13900048, 0x13900049, 0x1390004a, 0x1390004e,
	0x13900050, 0x13900052, 0x1390005c, 0x1390005d,
	0x13900060, 0x13900061, 0x13900063, 0x13900064,
	// Entry A0 - BF
	0x1390006d, 0x13900072, 0x13900073, 0x13900074,
	0x13900075, 0x1390007b, 0x1390007c, 0x1390007f,
	0x13900080, 0x13900081, 0x13900083, 0x1390008a,
	0x1390008c, 0x1390008d, 0x13900096, 0x13900097,
	0x13900098, 0x13900099, 0x1390009a, 0x1390009f,
	0x139000a0, 0x139000a4, 0x139000a7, 0x139000a9,
	0x139000ad, 0x139000b1, 0x139000b4, 0x139000b5,
	0x139000bf, 0x139000c0, 0x139000c6, 0x139000c7,
	// Entry C0 - DF
	0x139000ca, 0x139000cb, 0x139000cc, 0x139000ce,
	0x139000d0, 0x139000d2, 0x139000d5, 0x139000d6,
	0x139000d9, 0x139000dd, 0x139000df, 0x139000e0,
	0x139000e6, 0x139000e7, 0x139000e8, 0x139000eb,
	0x139000ec, 0x139000f0, 0x13900107, 0x13900109,
	0x1390010a, 0x1390010b, 0x1390010c, 0x1390010d,
	0x1390010e, 0x1390010f, 0x13900112, 0x13900117,
	0x1390011b, 0x1390011d, 0x1390011f, 0x13900125,
	// Entry E0 - FF
	0x13900129, 0x1390012c, 0x1390012d, 0x1390012f,
	0x13900131, 0x13900133, 0x13900135, 0x13900139,
	0x1390013c, 0x1390013d, 0x1390013f, 0x13900142,
	0x13900161, 0x13900162, 0x13900164, 0x13c00000,
	0x13c00001, 0x13e00000, 0x13e0001f, 0x13e0002c,
	0x13e0003f, 0x13e00041, 0x13e00048, 0x13e00051,
	0x13e00054, 0x13e00056, 0x13e00059, 0x13e00065,
	0x13e00068, 0x13e00069, 0x13e0006e, 0x13e00086,
	// Entry 100 - 11F
	0x13e00089, 0x13e0008f, 0x13e00094, 0x13e000cf,
	0x13e000d8, 0x13e000e2, 0x13e000e4, 0x13e000e7,
	0x13e000ec, 0x13e000f1, 0x13e0011a, 0x13e00135,
	0x13e00136, 0x13e0013b, 0x14000000, 0x1400006a,
	0x14500000, 0x1450006e, 0x14600000, 0x14600052,
	0x14800000, 0x14800024, 0x1480009c, 0x14e00000,
	0x14e00052, 0x14e00084, 0x14e000c9, 0x14e00114,
	0x15100000, 0x15100072, 0x15300000, 0x153000e7,
	// Entry 120 - 13F
	0x15800000, 0x15800063, 0x15800076, 0x15e00000,
	0x15e00036, 0x15e00037, 0x15e0003a, 0x15e0003b,
	0x15e0003c, 0x15e00049, 0x15e0004b, 0x15e0004c,
	0x15e0004d, 0x15e0004e, 0x15e0004f, 0x15e00052,
	0x15e00062, 0x15e00067, 0x15e00078, 0x15e0007a,
	0x15e0007e, 0x15e00084, 0x15e00085, 0x15e00086,
	0x15e00091, 0x15e000a8, 0x15e000b7, 0x15e000ba,
	0x15e000bb, 0x15e000be, 0x15e000bf, 0x15e000c3,
	// Entry 140 - 15F
	0x15e000c8, 0x15e000c9, 0x15e000cc, 0x15e000d3,
	0x15e000d4, 0x15e000e5, 0x15e000ea, 0x15e00102,
	0x15e00107, 0x15e0010a, 0x15e00114, 0x15e0011c,
	0x15e00120, 0x15e00122, 0x15e00128, 0x15e0013f,
	0x15e00140, 0x15e0015f, 0x16900000, 0x1690009e,
	0x16d00000, 0x16d000d9, 0x16e00000, 0x16e00096,
	0x17e00000, 0x17e0007b, 0x19000000, 0x1900006e,
	0x1a300000, 0x1a30004e, 0x1a300078, 0x1a3000b2,
	// Entry 160 - 17F
	0x1a400000, 0x1a400099, 0x1a900000, 0x1ab00000,
	0x1ab000a4, 0x1ac00000, 0x1ac00098, 0x1b400000,
	0x1b400080, 0x1b4000d4, 0x1b4000d6, 0x1b800000,
	0x1b800135, 0x1bc00000, 0x1bc00097, 0x1be00000,
	0x1be00099, 0x1d100000, 0x1d100033, 0x1d100090,
	0x1d200000, 0x1d200060, 0x1d500000, 0x1d500092,
	0x1d700000, 0x1d700028, 0x1e100000, 0x1e100095,
	0x1e700000, 0x1e7000d6, 0x1ea00000, 0x1ea00053,
	// Entry 180 - 19F
	0x1f300000, 0x1f500000, 0x1f800000, 0x1f80009d,
	0x1f900000, 0x1f90004e, 0x1f90009e, 0x1f900113,
	0x1f900138, 0x1fa00000, 0x1fb00000, 0x20000000,
	0x200000a2, 0x20300000, 0x20700000, 0x20700052,
	0x20800000, 0x20a00000, 0x20a0012f, 0x20e00000,
	0x20f00000, 0x21000000, 0x2100007d, 0x21200000,
	0x21200067, 0x21600000, 0x21700000, 0x217000a4,
	0x21f00000, 0x22300000, 0x2230012f, 0x22700000,
	// Entry 1A0 - 1BF
	0x2270005a, 0x23400000, 0x234000c3, 0x23900000,
	0x239000a4, 0x24200000, 0x242000ae, 0x24400000,
	0x24400052, 0x24500000, 0x24500082, 0x24600000,
	0x246000a4, 0x24a00000, 0x24a000a6, 0x25100000,
	0x25100099, 0x25400000, 0x254000aa, 0x254000ab,
	0x25600000, 0x25600099, 0x26a00000, 0x26a00099,
	0x26b00000, 0x26b0012f, 0x26d00000, 0x26d00052,
	0x26e00000, 0x26e00060, 0x27400000, 0x28100000,
	// Entry 1C0 - 1DF
	0x2810007b, 0x28a00000, 0x28a000a5, 0x29100000,
	0x2910012f, 0x29500000, 0x295000b7, 0x2a300000,
	0x2a300131, 0x2af00000, 0x2af00135, 0x2b500000,
	0x2b50002a, 0x2b50004b, 0x2b50004c, 0x2b50004d,
	0x2b800000, 0x2b8000af, 0x2bf00000, 0x2bf0009b,
	0x2bf0009c, 0x2c000000, 0x2c0000b6, 0x2c200000,
	0x2c20004b, 0x2c400000, 0x2c4000a4, 0x2c500000,
	0x2c5000a4, 0x2c700000, 0x2c7000b8, 0x2d100000,
	// Entry 1E0 - 1FF
	0x2d1000a4, 0x2d10012f, 0x2e900000, 0x2e9000a4,
	0x2ed00000, 0x2ed000cc, 0x2f100000, 0x2f1000bf,
	0x2f200000, 0x2f2000d1, 0x2f400000, 0x2f400052,
	0x2ff00000, 0x2ff000c2, 0x30400000, 0x30400099,
	0x30b00000, 0x30b000c5, 0x31000000, 0x31b00000,
	0x31b00099, 0x31f00000, 0x31f0003e, 0x31f000d0,
	0x31f0010d, 0x32000000, 0x320000cb, 0x32500000,
	0x32500052, 0x33100000, 0x331000c4, 0x33a00000,
	// Entry 200 - 21F
	0x33a0009c, 0x34100000, 0x34500000, 0x345000d2,
	0x34700000, 0x347000da, 0x34700110, 0x34e00000,
	0x34e00164, 0x35000000, 0x35000060, 0x350000d9,
	0x35100000, 0x35100099, 0x351000db, 0x36700000,
	0x36700030, 0x36700036, 0x36700040, 0x3670005b,
	0x367000d9, 0x36700116, 0x3670011b, 0x36800000,
	0x36800052, 0x36a00000, 0x36a000da, 0x36c00000,
	0x36c00052, 0x36f00000, 0x37500000, 0x37600000,
	// Entry 220 - 23F
	0x37a00000, 0x38000000, 0x38000117, 0x38700000,
	0x38900000, 0x38900131, 0x39000000, 0x3900006f,
	0x390000a4, 0x39500000, 0x39500099, 0x39800000,
	0x3980007d, 0x39800106, 0x39d00000, 0x39d05000,
	0x39d050e8, 0x39d33000, 0x39d33099, 0x3a100000,
	0x3b300000, 0x3b3000e9, 0x3bd00000, 0x3bd00001,
	0x3be00000, 0x3be00024, 0x3c000000, 0x3c00002a,
	0x3c000041, 0x3c00004e, 0x3c00005a, 0x3c000086,
	// Entry 240 - 25F
	0x3c00008b, 0x3c0000b7, 0x3c0000c6, 0x3c0000d1,
	0x3c0000ee, 0x3c000118, 0x3c000126, 0x3c400000,
	0x3c40003f, 0x3c400069, 0x3c4000e4, 0x3d400000,
	0x3d40004e, 0x3d900000, 0x3d90003a, 0x3dc00000,
	0x3dc000bc, 0x3dc00104, 0x3de00000, 0x3de0012f,
	0x3e200000, 0x3e200047, 0x3e2000a5, 0x3e2000ae,
	0x3e2000bc, 0x3e200106, 0x3e200130, 0x3e500000,
	0x3e500107, 0x3e600000, 0x3e60012f, 0x3eb00000,
	// Entry 260 - 27F
	0x3eb00106, 0x3ec00000, 0x3ec000a4, 0x3f300000,
	0x3f30012f, 0x3fa00000, 0x3fa000e8, 0x3fc00000,
	0x3fd00000, 0x3fd00072, 0x3fd000da, 0x3fd0010c,
	0x3ff00000, 0x3ff000d1, 0x40100000, 0x401000c3,
	0x40200000, 0x4020004c, 0x40700000, 0x40800000,
	0x40857000, 0x408570ba, 0x408dc000, 0x408dc0ba,
	0x40c00000, 0x40c000b3, 0x41200000, 0x41200111,
	0x41600000, 0x4160010f, 0x41c00000, 0x41d00000,
	// Entry 280 - 29F
	0x41e00000, 0x41f00000, 0x41f00072, 0x42200000,
	0x42300000, 0x42300164, 0x42900000, 0x42900062,
	0x4290006f, 0x429000a4, 0x42900115, 0x43100000,
	0x43100027, 0x431000c2, 0x4310014d, 0x43200000,
	0x4321f000, 0x4321f033, 0x4321f0bd, 0x4321f105,
	0x4321f14d, 0x43257000, 0x43257033, 0x432570bd,
	0x43257105, 0x4325714d, 0x43700000, 0x43a00000,
	0x43b00000, 0x44400000, 0x44400031, 0x44400072,
	// Entry 2A0 - 2BF
	0x4440010c, 0x44500000, 0x4450004b, 0x445000a4,
	0x4450012f, 0x44500131, 0x44e00000, 0x45000000,
	0x45000099, 0x450000b3, 0x450000d0, 0x4500010d,
	0x46100000, 0x46100099, 0x46400000, 0x464000a4,
	0x46400131, 0x46700000, 0x46700124, 0x46b00000,
	0x46b00123, 0x46f00000, 0x46f0006d, 0x46f0006f,
	0x47100000, 0x47600000, 0x47600127, 0x47a00000,
	0x48000000, 0x48200000, 0x48200129, 0x48a00000,
	// Entry 2C0 - 2DF
	0x48a0005d, 0x48a0012b, 0x48e00000, 0x49400000,
	0x49400106, 0x4a400000, 0x4a4000d4, 0x4a900000,
	0x4a9000ba, 0x4ac00000, 0x4ac00053, 0x4ae00000,
	0x4ae00130, 0x4b400000, 0x4b400099, 0x4b4000e8,
	0x4bc00000, 0x4bc05000, 0x4bc05024, 0x4bc1f000,
	0x4bc1f137, 0x4bc57000, 0x4bc57137, 0x4be00000,
	0x4be57000, 0x4be570b4, 0x4bee3000, 0x4bee30b4,
	0x4c000000, 0x4c300000, 0x4c30013e, 0x4c900000,
	// Entry 2E0 - 2FF
	0x4c900001, 0x4cc00000, 0x4cc0012f, 0x4ce00000,
	0x4cf00000, 0x4cf0004e, 0x4e500000, 0x4e500114,
	0x4f200000, 0x4fb00000, 0x4fb00131, 0x50900000,
	0x50900052, 0x51200000, 0x51200001, 0x51800000,
	0x5180003b, 0x518000d6, 0x51f00000, 0x51f38000,
	0x51f38053, 0x51f39000, 0x51f3908d, 0x52800000,
	0x528000ba, 0x52900000, 0x52938000, 0x52938053,
	0x5293808d, 0x529380c6, 0x5293810d, 0x52939000,
	// Entry 300 - 31F
	0x5293908d, 0x529390c6, 0x5293912e, 0x52f00000,
	0x52f00161,
} // Size: 3116 bytes

const specialTagsStr string = "ca-ES-valencia en-US-u-va-posix"

var regionToGroups = []uint8{ // 357 elements
	// Entry 0 - 3F
	0x00, 0x00, 0x00, 0x04, 0x04, 0x00, 0x00, 0x04,
	0x00, 0x00, 0x00, 0x00, 0x04, 0x04, 0x04, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x04, 0x00,
	0x00, 0x04, 0x00, 0x00, 0x04, 0x01, 0x00, 0x00,
	0x04, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x04, 0x04, 0x00, 0x04,
	// Entry 40 - 7F
	0x04, 0x04, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x04, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x04, 0x00, 0x00, 0x04, 0x00, 0x04, 0x00,
	0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x04, 0x04, 0x00, 0x08,
	0x00, 0x04, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x04, 0x00,
	// Entry 80 - BF
	0x00, 0x00, 0x04, 0x00, 0x00, 0x04, 0x00, 0x00,
	0x00, 0x04, 0x01, 0x00, 0x04, 0x02, 0x00, 0x04,
	0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x04, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00,
	0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x08, 0x08, 0x00, 0x00, 0x00, 0x04, 0x00,
	// Entry C0 - FF
	0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x01,
	0x04, 0x08, 0x04, 0x00, 0x00, 0x00, 0x00, 0x04,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x04, 0x00, 0x05, 0x00, 0x00, 0x00,
	0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	// Entry 100 - 13F
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00,
	0x00, 0x00, 0x04, 0x04, 0x00, 0x00, 0x00, 0x04,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x08, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x01, 0x00, 0x05, 0x04, 0x00,
	0x00, 0x04, 0x00, 0x04, 0x04, 0x05, 0x00, 0x00,
	// Entry 140 - 17F
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00,
} // Size: 381 bytes

var paradigmLocales = [][3]uint16{ // 3 elements
	0: [3]uint16{0x139, 0x0, 0x7b},
	1: [3]uint16{0x13e, 0x0, 0x1f},
	2: [3]uint16{0x3c0, 0x41, 0xee},
} // Size: 42 bytes

type mutualIntelligibility struct {
	want     uint16
	have     uint16
	distance uint8
	oneway   bool
}
type scriptIntelligibility struct {
	wantLang   uint16
	haveLang   uint16
	wantScript uint8
	haveScript uint8
	distance   uint8
}
type regionIntelligibility struct {
	lang     uint16
	script   uint8
	group    uint8
	distance uint8
}

// matchLang holds pairs of langIDs of base languages that are typically
// mutually intelligible. Each pair is associated with a confidence and
// whether the intelligibility goes one or both ways.
var matchLang = []mutualIntelligibility{ // 113 elements
	0:   {want: 0x1d1, have: 0xb7, distance: 0x4, oneway: false},
	1:   {want: 0x407, have: 0xb7, distance: 0x4, oneway: false},
	2:   {want: 0x407, have: 0x1d1, distance: 0x4, oneway: false},
	3:   {want: 0x407, have: 0x432, distance: 0x4, oneway: false},
	4:   {want: 0x43a, have: 0x1, distance: 0x4, oneway: false},
	5:   {want: 0x1a3, have: 0x10d, distance: 0x4, oneway: true},
	6:   {want: 0x295, have: 0x10d, distance: 0x4, oneway: true},
	7:   {want: 0x101, have: 0x36f, distance: 0x8, oneway: false},
	8:   {want: 0x101, have: 0x347, distance: 0x8, oneway: false},
	9:   {want: 0x5, have: 0x3e2, distance: 0xa, oneway: true},
	10:  {want: 0xd, have: 0x139, distance: 0xa, oneway: true},
	11:  {want: 0x16, have: 0x367, distance: 0xa, oneway: true},
	12:  {want: 0x21, have: 0x139, distance: 0xa, oneway: true},
	13:  {want: 0x56, have: 0x13e, distance: 0xa, oneway: true},
	14:  {want: 0x58, have: 0x3e2, distance: 0xa, oneway: true},
	15:  {want: 0x71, have: 0x3e2, distance: 0xa, oneway: true},
	16:  {want: 0x75, have: 0x139, distance: 0xa, oneway: true},
	17:  {want: 0x82, have: 0x1be, distance: 0xa, oneway: true},
	18:  {want: 0xa5, have: 0x139, distance: 0xa, oneway: true},
	19:  {want: 0xb2, have: 0x15e, distance: 0xa, oneway: true},
	20:  {want: 0xdd, have: 0x153, distance: 0xa, oneway: true},
	21:  {want: 0xe5, have: 0x139, distance: 0xa, oneway: true},
	22:  {want: 0xe9, have: 0x3a, distance: 0xa, oneway: true},
	23:  {want: 0xf0, have: 0x15e, distance: 0xa, oneway: true},
	24:  {want: 0xf9, have: 0x15e, distance: 0xa, oneway: true},
	25:  {want: 0x100, have: 0x139, distance: 0xa, oneway: true},
	26:  {want: 0x130, have: 0x139, distance: 0xa, oneway: true},
	27:  {want: 0x13c, have: 0x139, distance: 0xa, oneway: true},
	28:  {want: 0x140, have: 0x151, distance: 0xa, oneway: true},
	29:  {want: 0x145, have: 0x13e, distance: 0xa, oneway: true},
	30:  {want: 0x158, have: 0x101, distance: 0xa, oneway: true},
	31:  {want: 0x16d, have: 0x367, distance: 0xa, oneway: true},
	32:  {want: 0x16e, have: 0x139, distance: 0xa, oneway: true},
	33:  {want: 0x16f, have: 0x139, distance: 0xa, oneway: true},
	34:  {want: 0x17e, have: 0x139, distance: 0xa, oneway: true},
	35:  {want: 0x190, have: 0x13e, distance: 0xa, oneway: true},
	36:  {want: 0x194, have: 0x13e, distance: 0xa, oneway: true},
	37:  {want: 0x1a4, have: 0x1be, distance: 0xa, oneway: true},
	38:  {want: 0x1b4, have: 0x139, distance: 0xa, oneway: true},
	39:  {want: 0x1b8, have: 0x139, distance: 0xa, oneway: true},
	40:  {want: 0x1d4, have: 0x15e, distance: 0xa, oneway: true},
	41:  {want: 0x1d7, have: 0x3e2, distance: 0xa, oneway: true},
	42:  {want: 0x1d9, have: 0x139, distance: 0xa, oneway: true},
	43:  {want: 0x1e7, have: 0x139, distance: 0xa, oneway: true},
	44:  {want: 0x1f8, have: 0x139, distance: 0xa, oneway: true},
	45:  {want: 0x20e, have: 0x1e1, distance: 0xa, oneway: true},
	46:  {want: 0x210, have: 0x139, distance: 0xa, oneway: true},
	47:  {want: 0x22d, have: 0x15e, distance: 0xa, oneway: true},
	48:  {want: 0x242, have: 0x3e2, distance: 0xa, oneway: true},
	49:  {want: 0x24a, have: 0x139, distance: 0xa, oneway: true},
	50:  {want: 0x251, have: 0x139, distance: 0xa, oneway: true},
	51:  {want: 0x265, have: 0x139, distance: 0xa, oneway: true},
	52:  {want: 0x274, have: 0x48a, distance: 0xa, oneway: true},
	53:  {want: 0x28a, have: 0x3e2, distance: 0xa, oneway: true},
	54:  {want: 0x28e, have: 0x1f9, distance: 0xa, oneway: true},
	55:  {want: 0x2a3, have: 0x139, distance: 0xa, oneway: true},
	56:  {want: 0x2b5, have: 0x15e, distance: 0xa, oneway: true},
	57:  {want: 0x2b8, have: 0x139, distance: 0xa, oneway: true},
	58:  {want: 0x2be, have: 0x139, distance: 0xa, oneway: true},
	59:  {want: 0x2c3, have: 0x15e, distance: 0xa, oneway: true},
	60:  {want: 0x2ed, have: 0x139, distance: 0xa, oneway: true},
	61:  {want: 0x2f1, have: 0x15e, distance: 0xa, oneway: true},
	62:  {want: 0x2fa, have: 0x139, distance: 0xa, oneway: true},
	63:  {want: 0x2ff, have: 0x7e, distance: 0xa, oneway: true},
	64:  {want: 0x304, have: 0x139, distance: 0xa, oneway: true},
	65:  {want: 0x30b, have: 0x3e2, distance: 0xa, oneway: true},
	66:  {want: 0x31b, have: 0x1be, distance: 0xa, oneway: true},
	67:  {want: 0x31f, have: 0x1e1, distance: 0xa, oneway: true},
	68:  {want: 0x320, have: 0x139, distance: 0xa, oneway: true},
	69:  {want: 0x331, have: 0x139, distance: 0xa, oneway: true},
	70:  {want: 0x351, have: 0x139, distance: 0xa, oneway: true},
	71:  {want: 0x36a, have: 0x347, distance: 0xa, oneway: false},
	72:  {want: 0x36a, have: 0x36f, distance: 0xa, oneway: true},
	73:  {want: 0x37a, have: 0x139, distance: 0xa, oneway: true},
	74:  {want: 0x387, have: 0x139, distance: 0xa, oneway: true},
	75:  {want: 0x389, have: 0x139, distance: 0xa, oneway: true},
	76:  {want: 0x38b, have: 0x15e, distance: 0xa, oneway: true},
	77:  {want: 0x390, have: 0x139, distance: 0xa, oneway: true},
	78:  {want: 0x395, have: 0x139, distance: 0xa, oneway: true},
	79:  {want: 0x39d, have: 0x139, distance: 0xa, oneway: true},
	80:  {want: 0x3a5, have: 0x139, distance: 0xa, oneway: true},
	81:  {want: 0x3be, have: 0x139, distance: 0xa, oneway: true},
	82:  {want: 0x3c4, have: 0x13e, distance: 0xa, oneway: true},
	83:  {want: 0x3d4, have: 0x10d, distance: 0xa, oneway: true},
	84:  {want: 0x3d9, have: 0x139, distance: 0xa, oneway: true},
	85:  {want: 0x3e5, have: 0x15e, distance: 0xa, oneway: true},
	86:  {want: 0x3e9, have: 0x1be, distance: 0xa, oneway: true},
	87:  {want: 0x3fa, have: 0x139, distance: 0xa, oneway: true},
	88:  {want: 0x40c, have: 0x139, distance: 0xa, oneway: true},
	89:  {want: 0x423, have: 0x139, distance: 0xa, oneway: true},
	90:  {want: 0x429, have: 0x139, distance: 0xa, oneway: true},
	91:  {want: 0x431, have: 0x139, distance: 0xa, oneway: true},
	92:  {want: 0x43b, have: 0x139, distance: 0xa, oneway: true},
	93:  {want: 0x43e, have: 0x1e1, distance: 0xa, oneway: true},
	94:  {want: 0x445, have: 0x139, distance: 0xa, oneway: true},
	95:  {want: 0x450, have: 0x139, distance: 0xa, oneway: true},
	96:  {want: 0x461, have: 0x139, distance: 0xa, oneway: true},
	97:  {want: 0x467, have: 0x3e2, distance: 0xa, oneway: true},
	98:  {want: 0x46f, have: 0x139, distance: 0xa, oneway: true},
	99:  {want: 0x476, have: 0x3e2, distance: 0xa, oneway: true},
	100: {want: 0x3883, have: 0x139, distance: 0xa, oneway: true},
	101: {want: 0x480, have: 0x139, distance: 0xa, oneway: true},
	102: {want: 0x482, have: 0x139, distance: 0xa, oneway: true},
	103: {want: 0x494, have: 0x3e2, distance: 0xa, oneway: true},
	104: {want: 0x49d, have: 0x139, distance: 0xa, oneway: true},
	105: {want: 0x4ac, have: 0x529, distance: 0xa, oneway: true},
	106: {want: 0x4b4, have: 0x139, distance: 0xa, oneway: true},
	107: {want: 0x4bc, have: 0x3e2, distance: 0xa, oneway: true},
	108: {want: 0x4e5, have: 0x15e, distance: 0xa, oneway: true},
	109: {want: 0x4f2, have: 0x139, distance: 0xa, oneway: true},
	110: {want: 0x512, have: 0x139, distance: 0xa, oneway: true},
	111: {want: 0x518, have: 0x139, distance: 0xa, oneway: true},
	112: {want: 0x52f, have: 0x139, distance: 0xa, oneway: true},
} // Size: 702 bytes

// matchScript holds pairs of scriptIDs where readers of one script
// can typically also read the other. Each is associated with a confidence.
var matchScript = []scriptIntelligibility{ // 26 elements
	0:  {wantLang: 0x432, haveLang: 0x432, wantScript: 0x57, haveScript: 0x1f, distance: 0x5},
	1:  {wantLang: 0x432, haveLang: 0x432, wantScript: 0x1f, haveScript: 0x57, distance: 0x5},
	2:  {wantLang: 0x58, haveLang: 0x3e2, wantScript: 0x57, haveScript: 0x1f, distance: 0xa},
	3:  {wantLang: 0xa5, haveLang: 0x139, wantScript: 0xe, haveScript: 0x57, distance: 0xa},
	4:  {wantLang: 0x1d7, haveLang: 0x3e2, wantScript: 0x8, haveScript: 0x1f, distance: 0xa},
	5:  {wantLang: 0x210, haveLang: 0x139, wantScript: 0x2b, haveScript: 0x57, distance: 0xa},
	6:  {wantLang: 0x24a, haveLang: 0x139, wantScript: 0x4b, haveScript: 0x57, distance: 0xa},
	7:  {wantLang: 0x251, haveLang: 0x139, wantScript: 0x4f, haveScript: 0x57, distance: 0xa},
	8:  {wantLang: 0x2b8, haveLang: 0x139, wantScript: 0x54, haveScript: 0x57, distance: 0xa},
	9:  {wantLang: 0x304, haveLang: 0x139, wantScript: 0x6b, haveScript: 0x57, distance: 0xa},
	10: {wantLang: 0x331, haveLang: 0x139, wantScript: 0x72, haveScript: 0x57, distance: 0xa},
	11: {wantLang: 0x351, haveLang: 0x139, wantScript: 0x21, haveScript: 0x57, distance: 0xa},
	12: {wantLang: 0x395, haveLang: 0x139, wantScript: 0x7d, haveScript: 0x57, distance: 0xa},
	13: {wantLang: 0x39d, haveLang: 0x139, wantScript: 0x33, haveScript: 0x57, distance: 0xa},
	14: {wantLang: 0x3be, haveLang: 0x139, wantScript: 0x5, haveScript: 0x57, distance: 0xa},
	15: {wantLang: 0x3fa, haveLang: 0x139, wantScript: 0x5, haveScript: 0x57, distance: 0xa},
	16: {wantLang: 0x40c, haveLang: 0x139, wantScript: 0xca, haveScript: 0x57, distance: 0xa},
	17: {wantLang: 0x450, haveLang: 0x139, wantScript: 0xd7, haveScript: 0x57, distance: 0xa},
	18: {wantLang: 0x461, haveLang: 0x139, wantScript: 0xda, haveScript: 0x57, distance: 0xa},
	19: {wantLang: 0x46f, haveLang: 0x139, wantScript: 0x29, haveScript: 0x57, distance: 0xa},
	20: {wantLang: 0x476, haveLang: 0x3e2, wantScript: 0x57, haveScript: 0x1f, distance: 0xa},
	21: {wantLang: 0x4b4, haveLang: 0x139, wantScript: 0x5, haveScript: 0x57, distance: 0xa},
	22: {wantLang: 0x4bc, haveLang: 0x3e2, wantScript: 0x57, haveScript: 0x1f, distance: 0xa},
	23: {wantLang: 0x512, haveLang: 0x139, wantScript: 0x3b, haveScript: 0x57, distance: 0xa},
	24: {wantLang: 0x529, haveLang: 0x529, wantScript: 0x38, haveScript: 0x39, distance: 0xf},
	25: {wantLang: 0x529, haveLang: 0x529, wantScript: 0x39, haveScript: 0x38, distance: 0x13},
} // Size: 232 bytes

var matchRegion = []regionIntelligibility{ // 15 elements
	0:  {lang: 0x3a, script: 0x0, group: 0x4, distance: 0x4},
	1:  {lang: 0x3a, script: 0x0, group: 0x84, distance: 0x4},
	2:  {lang: 0x139, script: 0x0, group: 0x1, distance: 0x4},
	3:  {lang: 0x139, script: 0x0, group: 0x81, distance: 0x4},
	4:  {lang: 0x13e, script: 0x0, group: 0x3, distance: 0x4},
	5:  {lang: 0x13e, script: 0x0, group: 0x83, distance: 0x4},
	6:  {lang: 0x3c0, script: 0x0, group: 0x3, distance: 0x4},
	7:  {lang: 0x3c0, script: 0x0, group: 0x83, distance: 0x4},
	8:  {lang: 0x529, script: 0x39, group: 0x2, distance: 0x4},
	9:  {lang: 0x529, script: 0x39, group: 0x82, distance: 0x4},
	10: {lang: 0x3a, script: 0x0, group: 0x80, distance: 0x5},
	11: {lang: 0x139, script: 0x0, group: 0x80, distance: 0x5},
	12: {lang: 0x13e, script: 0x0, group: 0x80, distance: 0x5},
	13: {lang: 0x3c0, script: 0x0, group: 0x80, distance: 0x5},
	14: {lang: 0x529, script: 0x39, group: 0x80, distance: 0x5},
} // Size: 114 bytes

// Total table size 4618 bytes (4KiB); checksum: D161A896
