// This file was generated by go generate; DO NOT EDIT

package precis

type property int

// The order of these constants matter. A Profile may consider runes to be
// allowed either from pValid or idDisOrFreePVal.
const (
	unassigned property = iota
	disallowed
	contextO
	contextJ
	idDisOrFreePVal
	pValid
)
