// This file was generated by go generate; DO NOT EDIT

package currency

import "golang.org/x/text/internal/tag"

// CLDRVersion is the CLDR version from which the tables in this package are derived.
const CLDRVersion = "27.0.1"

const (
	xxx = 281
	xts = 279
	usd = 248
	eur = 92
	jpy = 131
	gbp = 97
	chf = 60
	aud = 19
	nzd = 189
	cad = 57
	sek = 216
	nok = 187
	dkk = 80
	xag = 262
	xau = 263
	xpt = 276
	xpd = 274
	brl = 46
	cny = 66
	inr = 123
	rub = 207
	hkd = 112
	idr = 118
	krw = 139
	mxn = 175
	pln = 198
	sar = 210
	thb = 231
	try = 240
	twd = 242
	zar = 289
)

// currency holds an alphabetically sorted list of canonical 3-letter currency
// identifiers. Each identifier is followed by a byte of type currencyInfo,
// defined in gen_common.go.
// Size: 1192 bytes
const currency tag.Index = "" +
	"\x00\x00\x00\x00ADP\x01AED\x00AFA\x00AFN\x01ALK\x00ALL\x01AMD\x01ANG\x00" +
	"AOA\x00AOK\x00AON\x00AOR\x00ARA\x00ARL\x00ARM\x00ARP\x00ARS\x00ATS\x00AU" +
	"D\x00AWG\x00AZM\x00AZN\x00BAD\x00BAM\x00BAN\x00BBD\x00BDT\x00BEC\x00BEF" +
	"\x00BEL\x00BGL\x00BGM\x00BGN\x00BGO\x00BHD\x03BIF\x01BMD\x00BND\x00BOB" +
	"\x00BOL\x00BOP\x00BOV\x00BRB\x00BRC\x00BRE\x00BRL\x00BRN\x00BRR\x00BRZ" +
	"\x00BSD\x00BTN\x00BUK\x00BWP\x00BYB\x00BYR\x01BZD\x00CAD(CDF\x00CHE\x00C" +
	"HF(CHW\x00CLE\x00CLF\x04CLP\x01CNX\x00CNY\x00COP\x01COU\x00CRC\x01CSD" +
	"\x00CSK\x00CUC\x00CUP\x00CVE\x00CYP\x00CZK\x08DDM\x00DEM\x00DJF\x01DKK" +
	"\x00DOP\x00DZD\x00ECS\x00ECV\x00EEK\x00EGP\x00ERN\x00ESA\x00ESB\x00ESP" +
	"\x01ETB\x00EUR\x00FIM\x00FJD\x00FKP\x00FRF\x00GBP\x00GEK\x00GEL\x00GHC" +
	"\x00GHS\x00GIP\x00GMD\x00GNF\x01GNS\x00GQE\x00GRD\x00GTQ\x00GWE\x00GWP" +
	"\x00GYD\x01HKD\x00HNL\x00HRD\x00HRK\x00HTG\x00HUF\x08IDR\x01IEP\x00ILP" +
	"\x00ILR\x00ILS\x00INR\x00IQD\x01IRR\x01ISJ\x00ISK\x01ITL\x01JMD\x00JOD" +
	"\x03JPY\x01KES\x00KGS\x00KHR\x00KMF\x01KPW\x01KRH\x00KRO\x00KRW\x01KWD" +
	"\x03KYD\x00KZT\x00LAK\x01LBP\x01LKR\x00LRD\x00LSL\x00LTL\x00LTT\x00LUC" +
	"\x00LUF\x01LUL\x00LVL\x00LVR\x00LYD\x03MAD\x00MAF\x00MCF\x00MDC\x00MDL" +
	"\x00MGA\x01MGF\x01MKD\x00MKN\x00MLF\x00MMK\x01MNT\x01MOP\x00MRO\x01MTL" +
	"\x00MTP\x00MUR\x01MVR\x00MWK\x00MXN\x00MXP\x00MXV\x00MYR\x00MZE\x00MZM" +
	"\x00MZN\x00NAD\x00NGN\x00NIC\x00NIO\x00NLG\x00NOK\x00NPR\x00NZD\x00OMR" +
	"\x03PAB\x00PEI\x00PEN\x00PES\x00PGK\x00PHP\x00PKR\x01PLN\x00PLZ\x00PTE" +
	"\x00PYG\x01QAR\x00RHD\x00ROL\x00RON\x00RSD\x01RUB\x00RUR\x00RWF\x01SAR" +
	"\x00SBD\x00SCR\x00SDD\x00SDG\x00SDP\x00SEK\x00SGD\x00SHP\x00SIT\x00SKK" +
	"\x00SLL\x01SOS\x01SRD\x00SRG\x00SSP\x00STD\x01SUR\x00SVC\x00SYP\x01SZL" +
	"\x00THB\x00TJR\x00TJS\x00TMM\x01TMT\x00TND\x03TOP\x00TPE\x00TRL\x01TRY" +
	"\x00TTD\x00TWD\x08TZS\x01UAH\x00UAK\x00UGS\x00UGX\x01USD\x00USN\x00USS" +
	"\x00UYI\x01UYP\x00UYU\x00UZS\x01VEB\x00VEF\x00VND\x01VNN\x00VUV\x01WST" +
	"\x00XAF\x01XAG\x00XAU\x00XBA\x00XBB\x00XBC\x00XBD\x00XCD\x00XDR\x00XEU" +
	"\x00XFO\x00XFU\x00XOF\x01XPD\x00XPF\x01XPT\x00XRE\x00XSU\x00XTS\x00XUA" +
	"\x00XXX\x00YDD\x00YER\x01YUD\x00YUM\x00YUN\x00YUR\x00ZAL\x00ZAR\x00ZMK" +
	"\x01ZMW\x00ZRN\x00ZRZ\x00ZWD\x01ZWL\x00ZWR\x00\xff\xff\xff\xff"

const numCurrencies = 296

type toCurrency struct {
	region uint16
	code   uint16
}

// Size: 1044 bytes, 255 elements
var regionToCurrency = []toCurrency{
	{region: 0x4143, code: 0xda},
	{region: 0x4144, code: 0x5c},
	{region: 0x4145, code: 0x2},
	{region: 0x4146, code: 0x4},
	{region: 0x4147, code: 0x10c},
	{region: 0x4149, code: 0x10c},
	{region: 0x414c, code: 0x6},
	{region: 0x414d, code: 0x7},
	{region: 0x414f, code: 0x9},
	{region: 0x4152, code: 0x11},
	{region: 0x4153, code: 0xf8},
	{region: 0x4154, code: 0x5c},
	{region: 0x4155, code: 0x13},
	{region: 0x4157, code: 0x14},
	{region: 0x4158, code: 0x5c},
	{region: 0x415a, code: 0x16},
	{region: 0x4241, code: 0x18},
	{region: 0x4242, code: 0x1a},
	{region: 0x4244, code: 0x1b},
	{region: 0x4245, code: 0x5c},
	{region: 0x4246, code: 0x111},
	{region: 0x4247, code: 0x21},
	{region: 0x4248, code: 0x23},
	{region: 0x4249, code: 0x24},
	{region: 0x424a, code: 0x111},
	{region: 0x424c, code: 0x5c},
	{region: 0x424d, code: 0x25},
	{region: 0x424e, code: 0x26},
	{region: 0x424f, code: 0x27},
	{region: 0x4251, code: 0xf8},
	{region: 0x4252, code: 0x2e},
	{region: 0x4253, code: 0x32},
	{region: 0x4254, code: 0x33},
	{region: 0x4256, code: 0xbb},
	{region: 0x4257, code: 0x35},
	{region: 0x4259, code: 0x37},
	{region: 0x425a, code: 0x38},
	{region: 0x4341, code: 0x39},
	{region: 0x4343, code: 0x13},
	{region: 0x4344, code: 0x3a},
	{region: 0x4346, code: 0x105},
	{region: 0x4347, code: 0x105},
	{region: 0x4348, code: 0x3c},
	{region: 0x4349, code: 0x111},
	{region: 0x434b, code: 0xbd},
	{region: 0x434c, code: 0x40},
	{region: 0x434d, code: 0x105},
	{region: 0x434e, code: 0x42},
	{region: 0x434f, code: 0x43},
	{region: 0x4352, code: 0x45},
	{region: 0x4355, code: 0x49},
	{region: 0x4356, code: 0x4a},
	{region: 0x4357, code: 0x8},
	{region: 0x4358, code: 0x13},
	{region: 0x4359, code: 0x5c},
	{region: 0x435a, code: 0x4c},
	{region: 0x4445, code: 0x5c},
	{region: 0x4447, code: 0xf8},
	{region: 0x444a, code: 0x4f},
	{region: 0x444b, code: 0x50},
	{region: 0x444d, code: 0x10c},
	{region: 0x444f, code: 0x51},
	{region: 0x445a, code: 0x52},
	{region: 0x4541, code: 0x5c},
	{region: 0x4543, code: 0xf8},
	{region: 0x4545, code: 0x5c},
	{region: 0x4547, code: 0x56},
	{region: 0x4548, code: 0x9c},
	{region: 0x4552, code: 0x57},
	{region: 0x4553, code: 0x5c},
	{region: 0x4554, code: 0x5b},
	{region: 0x4555, code: 0x5c},
	{region: 0x4649, code: 0x5c},
	{region: 0x464a, code: 0x5e},
	{region: 0x464b, code: 0x5f},
	{region: 0x464d, code: 0xf8},
	{region: 0x464f, code: 0x50},
	{region: 0x4652, code: 0x5c},
	{region: 0x4741, code: 0x105},
	{region: 0x4742, code: 0x61},
	{region: 0x4744, code: 0x10c},
	{region: 0x4745, code: 0x63},
	{region: 0x4746, code: 0x5c},
	{region: 0x4747, code: 0x61},
	{region: 0x4748, code: 0x65},
	{region: 0x4749, code: 0x66},
	{region: 0x474c, code: 0x50},
	{region: 0x474d, code: 0x67},
	{region: 0x474e, code: 0x68},
	{region: 0x4750, code: 0x5c},
	{region: 0x4751, code: 0x105},
	{region: 0x4752, code: 0x5c},
	{region: 0x4753, code: 0x61},
	{region: 0x4754, code: 0x6c},
	{region: 0x4755, code: 0xf8},
	{region: 0x4757, code: 0x111},
	{region: 0x4759, code: 0x6f},
	{region: 0x484b, code: 0x70},
	{region: 0x484d, code: 0x13},
	{region: 0x484e, code: 0x71},
	{region: 0x4852, code: 0x73},
	{region: 0x4854, code: 0x74},
	{region: 0x4855, code: 0x75},
	{region: 0x4943, code: 0x5c},
	{region: 0x4944, code: 0x76},
	{region: 0x4945, code: 0x5c},
	{region: 0x494c, code: 0x7a},
	{region: 0x494d, code: 0x61},
	{region: 0x494e, code: 0x7b},
	{region: 0x494f, code: 0xf8},
	{region: 0x4951, code: 0x7c},
	{region: 0x4952, code: 0x7d},
	{region: 0x4953, code: 0x7f},
	{region: 0x4954, code: 0x5c},
	{region: 0x4a45, code: 0x61},
	{region: 0x4a4d, code: 0x81},
	{region: 0x4a4f, code: 0x82},
	{region: 0x4a50, code: 0x83},
	{region: 0x4b45, code: 0x84},
	{region: 0x4b47, code: 0x85},
	{region: 0x4b48, code: 0x86},
	{region: 0x4b49, code: 0x13},
	{region: 0x4b4d, code: 0x87},
	{region: 0x4b4e, code: 0x10c},
	{region: 0x4b50, code: 0x88},
	{region: 0x4b52, code: 0x8b},
	{region: 0x4b57, code: 0x8c},
	{region: 0x4b59, code: 0x8d},
	{region: 0x4b5a, code: 0x8e},
	{region: 0x4c41, code: 0x8f},
	{region: 0x4c42, code: 0x90},
	{region: 0x4c43, code: 0x10c},
	{region: 0x4c49, code: 0x3c},
	{region: 0x4c4b, code: 0x91},
	{region: 0x4c52, code: 0x92},
	{region: 0x4c53, code: 0x121},
	{region: 0x4c54, code: 0x5c},
	{region: 0x4c55, code: 0x5c},
	{region: 0x4c56, code: 0x5c},
	{region: 0x4c59, code: 0x9b},
	{region: 0x4d41, code: 0x9c},
	{region: 0x4d43, code: 0x5c},
	{region: 0x4d44, code: 0xa0},
	{region: 0x4d45, code: 0x5c},
	{region: 0x4d46, code: 0x5c},
	{region: 0x4d47, code: 0xa1},
	{region: 0x4d48, code: 0xf8},
	{region: 0x4d4b, code: 0xa3},
	{region: 0x4d4c, code: 0x111},
	{region: 0x4d4d, code: 0xa6},
	{region: 0x4d4e, code: 0xa7},
	{region: 0x4d4f, code: 0xa8},
	{region: 0x4d50, code: 0xf8},
	{region: 0x4d51, code: 0x5c},
	{region: 0x4d52, code: 0xa9},
	{region: 0x4d53, code: 0x10c},
	{region: 0x4d54, code: 0x5c},
	{region: 0x4d55, code: 0xac},
	{region: 0x4d56, code: 0xad},
	{region: 0x4d57, code: 0xae},
	{region: 0x4d58, code: 0xaf},
	{region: 0x4d59, code: 0xb2},
	{region: 0x4d5a, code: 0xb5},
	{region: 0x4e41, code: 0xb6},
	{region: 0x4e43, code: 0x113},
	{region: 0x4e45, code: 0x111},
	{region: 0x4e46, code: 0x13},
	{region: 0x4e47, code: 0xb7},
	{region: 0x4e49, code: 0xb9},
	{region: 0x4e4c, code: 0x5c},
	{region: 0x4e4f, code: 0xbb},
	{region: 0x4e50, code: 0xbc},
	{region: 0x4e52, code: 0x13},
	{region: 0x4e55, code: 0xbd},
	{region: 0x4e5a, code: 0xbd},
	{region: 0x4f4d, code: 0xbe},
	{region: 0x5041, code: 0xbf},
	{region: 0x5045, code: 0xc1},
	{region: 0x5046, code: 0x113},
	{region: 0x5047, code: 0xc3},
	{region: 0x5048, code: 0xc4},
	{region: 0x504b, code: 0xc5},
	{region: 0x504c, code: 0xc6},
	{region: 0x504d, code: 0x5c},
	{region: 0x504e, code: 0xbd},
	{region: 0x5052, code: 0xf8},
	{region: 0x5053, code: 0x7a},
	{region: 0x5054, code: 0x5c},
	{region: 0x5057, code: 0xf8},
	{region: 0x5059, code: 0xc9},
	{region: 0x5141, code: 0xca},
	{region: 0x5245, code: 0x5c},
	{region: 0x524f, code: 0xcd},
	{region: 0x5253, code: 0xce},
	{region: 0x5255, code: 0xcf},
	{region: 0x5257, code: 0xd1},
	{region: 0x5341, code: 0xd2},
	{region: 0x5342, code: 0xd3},
	{region: 0x5343, code: 0xd4},
	{region: 0x5344, code: 0xd6},
	{region: 0x5345, code: 0xd8},
	{region: 0x5347, code: 0xd9},
	{region: 0x5348, code: 0xda},
	{region: 0x5349, code: 0x5c},
	{region: 0x534a, code: 0xbb},
	{region: 0x534b, code: 0x5c},
	{region: 0x534c, code: 0xdd},
	{region: 0x534d, code: 0x5c},
	{region: 0x534e, code: 0x111},
	{region: 0x534f, code: 0xde},
	{region: 0x5352, code: 0xdf},
	{region: 0x5353, code: 0xe1},
	{region: 0x5354, code: 0xe2},
	{region: 0x5356, code: 0xf8},
	{region: 0x5358, code: 0x8},
	{region: 0x5359, code: 0xe5},
	{region: 0x535a, code: 0xe6},
	{region: 0x5441, code: 0x61},
	{region: 0x5443, code: 0xf8},
	{region: 0x5444, code: 0x105},
	{region: 0x5446, code: 0x5c},
	{region: 0x5447, code: 0x111},
	{region: 0x5448, code: 0xe7},
	{region: 0x544a, code: 0xe9},
	{region: 0x544b, code: 0xbd},
	{region: 0x544c, code: 0xf8},
	{region: 0x544d, code: 0xeb},
	{region: 0x544e, code: 0xec},
	{region: 0x544f, code: 0xed},
	{region: 0x5452, code: 0xf0},
	{region: 0x5454, code: 0xf1},
	{region: 0x5456, code: 0x13},
	{region: 0x5457, code: 0xf2},
	{region: 0x545a, code: 0xf3},
	{region: 0x5541, code: 0xf4},
	{region: 0x5547, code: 0xf7},
	{region: 0x554d, code: 0xf8},
	{region: 0x5553, code: 0xf8},
	{region: 0x5559, code: 0xfd},
	{region: 0x555a, code: 0xfe},
	{region: 0x5641, code: 0x5c},
	{region: 0x5643, code: 0x10c},
	{region: 0x5645, code: 0x100},
	{region: 0x5647, code: 0xf8},
	{region: 0x5649, code: 0xf8},
	{region: 0x564e, code: 0x101},
	{region: 0x5655, code: 0x103},
	{region: 0x5746, code: 0x113},
	{region: 0x5753, code: 0x104},
	{region: 0x584b, code: 0x5c},
	{region: 0x5945, code: 0x11b},
	{region: 0x5954, code: 0x5c},
	{region: 0x5a41, code: 0x121},
	{region: 0x5a4d, code: 0x123},
	{region: 0x5a57, code: 0xf8},
}

// Total table size 2236 bytes (2KiB); checksum: C9BB512B
