// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build ignore

// This program generates the trie for width operations. The generated table
// includes width category information as well as the normalization mappings.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"

	"golang.org/x/text/internal/triegen"
)

// See gen_common.go for flags.

func main() {
	flag.Parse()
	log.SetPrefix("")
	log.SetFlags(log.Lshortfile)
	genTables()
	repackage("gen_trieval.go", "trieval.go")
	repackage("gen_common.go", "common_test.go")
}

func genTables() {
	t := triegen.NewTrie("width")

	getWidthData(func(r rune, tag elem, alt rune) {
		t.Insert(r, uint64(tag|elem(alt&0x3FFF)))
	})

	w := &bytes.Buffer{}
	fmt.Fprintf(w, header)

	sz, err := t.Gen(w)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(w, "// Total table size %d bytes (%dKiB)\n", sz, sz/1024)

	out, err := format.Source(w.Bytes())
	if err != nil {
		log.Printf("Could not format output: %v", err)
		out = w.Bytes()
	}
	if err := ioutil.WriteFile(*outputFile, out, 0644); err != nil {
		log.Fatalf("Could not write output: %v", err)
	}
}

const header = `// This file was generated by go generate; DO NOT EDIT

package width

`

// repackage rewrites a file from belonging to package main to belonging to
// package width.
func repackage(inFile, outFile string) {
	src, err := ioutil.ReadFile(inFile)
	if err != nil {
		log.Fatalf("reading %s: %v", inFile, err)
	}
	const toDelete = "package main\n\n"
	i := bytes.Index(src, []byte(toDelete))
	if i < 0 {
		log.Fatalf("Could not find %q in gen_trieval.go", toDelete)
	}
	w := &bytes.Buffer{}
	fmt.Fprintf(w, header)
	w.Write(src[i+len(toDelete):])
	if err := ioutil.WriteFile(outFile, w.Bytes(), 0644); err != nil {
		log.Fatalf("Writing %s: %v", outFile, err)
	}
}
