// generated by stringer -type=Kind; DO NOT EDIT

package width

import "fmt"

const _Kind_name = "NeutralEastAsianAmbiguousEastAsianWideEastAsianNarrowEastAsianFullwidthEastAsianHalfwidth"

var _Kind_index = [...]uint8{7, 25, 38, 53, 71, 89}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	hi := _Kind_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Kind_index[i-1]
	}
	return _Kind_name[lo:hi]
}
