// generated by stringer -type=kind; DO NOT EDIT

package width

import "fmt"

const _kind_name = "neutralambiguouswidenarrowfullwidthhalfwidth"

var _kind_index = [...]uint8{7, 16, 20, 26, 35, 44}

func (i kind) String() string {
	if i < 0 || i >= kind(len(_kind_index)) {
		return fmt.Sprintf("kind(%d)", i)
	}
	hi := _kind_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _kind_index[i-1]
	}
	return _kind_name[lo:hi]
}
